In [1]:
#Dependencies
import numpy as np
import pandas as pd

In [20]:
#Pulling 201805 Data
Data_201805 = pd.read_csv('201805-citibike-tripdata.csv')
Data_201805.head(50)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,name_localizedValue0,usertype,birth year,gender
0,303,2018-05-01 00:00:11,2018-05-01 00:05:15,491,E 24 St & Park Ave S,40.740964,-73.986022,2003,1 Ave & E 18 St,40.733812,-73.980544,32191,$25 Off Annual Membership,Subscriber,1984.0,1
1,700,2018-05-01 00:00:36,2018-05-01 00:12:16,507,E 25 St & 2 Ave,40.739126,-73.979738,3458,W 55 St & 6 Ave,40.763094,-73.978350,29357,Annual Membership,Subscriber,1996.0,1
2,443,2018-05-01 00:00:40,2018-05-01 00:08:04,3263,Cooper Square & Astor Pl,40.729515,-73.990753,546,E 30 St & Park Ave S,40.744449,-73.983035,27255,Annual Membership,Subscriber,1969.0,1
3,297,2018-05-01 00:00:43,2018-05-01 00:05:41,532,S 5 Pl & S 5 St,40.710451,-73.960876,3096,Union Ave & N 12 St,40.719240,-73.952420,16980,Annual Membership,Subscriber,1985.0,1
4,421,2018-05-01 00:01:01,2018-05-01 00:08:02,3493,E 118 St & 3 Ave,40.799139,-73.938915,3351,E 102 St & 1 Ave,40.786995,-73.941648,30645,Annual Membership,Subscriber,1986.0,1
5,68905,2018-05-01 00:01:11,2018-05-01 19:09:36,237,E 11 St & 2 Ave,40.730473,-73.986724,504,1 Ave & E 16 St,40.732219,-73.981656,27440,Annual Membership,Subscriber,1969.0,1
6,197,2018-05-01 00:01:17,2018-05-01 00:04:35,437,Macon St & Nostrand Ave,40.680983,-73.950048,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,31566,Annual Membership,Subscriber,1988.0,1
7,259,2018-05-01 00:01:31,2018-05-01 00:05:50,236,St Marks Pl & 2 Ave,40.728419,-73.987140,312,Allen St & Stanton St,40.722055,-73.989111,29872,$25 Off Annual Membership,Subscriber,1996.0,2
8,359,2018-05-01 00:01:42,2018-05-01 00:07:42,3158,W 63 St & Broadway,40.771639,-73.982614,495,W 47 St & 10 Ave,40.762699,-73.993012,14824,Annual Membership,Subscriber,1981.0,2
9,460,2018-05-01 00:02:03,2018-05-01 00:09:43,285,Broadway & E 14 St,40.734546,-73.990741,236,St Marks Pl & 2 Ave,40.728419,-73.987140,17638,Annual Membership,Subscriber,1972.0,2
10,295,2018-05-01 00:02:04,2018-05-01 00:07:00,499,Broadway & W 60 St,40.769155,-73.981918,3175,W 70 St & Amsterdam Ave,40.777480,-73.982886,31475,Annual Membership,Subscriber,1958.0,1
11,204,2018-05-01 00:02:17,2018-05-01 00:05:42,3146,E 81 St & 3 Ave,40.775730,-73.956753,3135,E 75 St & 3 Ave,40.771129,-73.957723,14886,Annual Membership,Subscriber,1991.0,1
12,589,2018-05-01 00:02:22,2018-05-01 00:12:11,462,W 22 St & 10 Ave,40.746920,-74.004519,450,W 49 St & 8 Ave,40.762272,-73.987882,27251,Annual Membership,Subscriber,1981.0,1
13,90,2018-05-01 00:02:30,2018-05-01 00:04:00,3325,E 95 St & 3 Ave,40.784903,-73.950503,3312,1 Ave & E 94 St,40.781721,-73.945940,29077,Annual Membership,Subscriber,NaN,0
14,1596,2018-05-01 00:02:47,2018-05-01 00:29:24,439,E 4 St & 2 Ave,40.726281,-73.989780,3074,Montrose Ave & Bushwick Ave,40.707678,-73.940162,20843,Annual Membership from Citi Bike App,Subscriber,1995.0,1
15,342,2018-05-01 00:02:52,2018-05-01 00:08:34,474,5 Ave & E 29 St,40.745168,-73.986831,293,Lafayette St & E 8 St,40.730207,-73.991026,30253,Annual Membership,Subscriber,1991.0,1
16,905,2018-05-01 00:03:20,2018-05-01 00:18:25,3081,Graham Ave & Grand St,40.711863,-73.944024,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,30190,Annual Membership,Subscriber,1987.0,1
17,535,2018-05-01 00:03:28,2018-05-01 00:12:23,416,Cumberland St & Lafayette Ave,40.687534,-73.972652,373,Willoughby Ave & Walworth St,40.693317,-73.953820,29359,Annual Membership,Subscriber,1975.0,1
18,254,2018-05-01 00:03:30,2018-05-01 00:07:44,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,3087,Metropolitan Ave & Meeker Ave,40.714133,-73.952344,20523,Annual Membership,Subscriber,1972.0,1
19,352,2018-05-01 00:03:36,2018-05-01 00:09:29,403,E 2 St & 2 Ave,40.725029,-73.990697,150,E 2 St & Avenue C,40.720874,-73.980858,25750,Annual Membership,Subscriber,1995.0,1
20,686,2018-05-01 00:03:41,2018-05-01 00:15:07,468,Broadway & W 56 St,40.765265,-73.981923,3658,W 18 St & 9 Ave,40.743534,-74.003676,32316,Annual Membership,Subscriber,1982.0,1
21,297,2018-05-01 00:03:59,2018-05-01 00:08:57,498,Broadway & W 32 St,40.748549,-73.988084,527,E 33 St & 2 Ave,40.744023,-73.976056,28271,Annual Membership,Subscriber,1967.0,1
22,484,2018-05-01 00:04:27,2018-05-01 00:12:32,3419,Douglass St & 4 Ave,40.679279,-73.981540,3304,6 Ave & 9 St,40.668127,-73.983776,19678,Annual Membership,Subscriber,1978.0,1
23,1287,2018-05-01 00:05:06,2018-05-01 00:26:33,3529,Lenox Ave & W 130 St,40.810792,-73.943068,3529,Lenox Ave & W 130 St,40.810792,-73.943068,33068,24 Hour,Customer,NaN,0
24,1311,2018-05-01 00:05:18,2018-05-01 00:27:09,2003,1 Ave & E 18 St,40.733812,-73.980544,3140,1 Ave & E 78 St,40.771404,-73.953517,24888,$25 Off Annual Membership,Subscriber,1972.0,2
25,657,2018-05-01 00:05:20,2018-05-01 00:16:18,3335,Union St & 4 Ave,40.677274,-73.982820,3306,10 St & 7 Ave,40.666208,-73.981999,31596,Annual Membership,Subscriber,1980.0,1
26,184,2018-05-01 00:05:20,2018-05-01 00:08:25,3316,W 104 St & Amsterdam Ave,40.798994,-73.966217,3323,W 106 St & Central Park West,40.798186,-73.960591,17098,$25 Off Annual Membership,Subscriber,1993.0,1
27,1371,2018-05-01 00:05:32,2018-05-01 00:28:24,128,MacDougal St & Prince St,40.727103,-74.002971,481,S 3 St & Bedford Ave,40.712605,-73.962644,30618,$25 Off Annual Membership,Subscriber,1991.0,1
28,940,2018-05-01 00:05:45,2018-05-01 00:21:25,518,E 39 St & 2 Ave,40.747804,-73.973442,394,E 9 St & Avenue C,40.725213,-73.977688,25065,$25 Off Annual Membership,Subscriber,1991.0,1
29,317,2018-05-01 00:05:48,2018-05-01 00:11:05,435,W 21 St & 6 Ave,40.741740,-73.994156,285,Broadway & E 14 St,40.734546,-73.990741,29778,Annual Membership from Citi Bike App,Subscriber,1996.0,1
30,726,2018-05-01 00:05:51,2018-05-01 00:17:58,477,W 41 St & 8 Ave,40.756405,-73.990026,466,W 25 St & 6 Ave,40.743954,-73.991449,16394,Annual Membership,Subscriber,1969.0,1
31,971,2018-05-01 00:06:59,2018-05-01 00:23:10,439,E 4 St & 2 Ave,40.726281,-73.989780,435,W 21 St & 6 Ave,40.741740,-73.994156,32796,Annual Membership,Subscriber,1980.0,1
32,131,2018-05-01 00:07:11,2018-05-01 00:09:22,402,Broadway & E 22 St,40.740343,-73.989551,503,E 20 St & Park Ave,40.738274,-73.987520,32889,24 Hour,Customer,NaN,0
33,622,2018-05-01 00:07:13,2018-05-01 00:17:35,328,Watts St & Greenwich St,40.724055,-74.009660,361,Allen St & Hester St,40.716059,-73.991908,25563,Annual Membership,Subscriber,1972.0,1
34,428,2018-05-01 00:07:21,2018-05-01 00:14:29,3552,W 113 St & Broadway,40.805973,-73.964928,3350,W 100 St & Broadway,40.797372,-73.970412,17479,Annual Membership,Subscriber,1962.0,1
35,423,2018-05-01 00:07:30,2018-05-01 00:14:33,3552,W 113 St & Broadway,40.805973,-73.964928,3350,W 100 St & Broadway,40.797372,-73.970412,19562,Annual Membership,Subscriber,1970.0,2
36,319,2018-05-01 00:07:34,2018-05-01 00:12:54,302,Avenue D & E 3 St,40.720828,-73.977932,311,Norfolk St & Broome St,40.717227,-73.988021,25177,Annual Membership,Subscriber,1986.0,2
37,1330,2018-05-01 00:07:37,2018-05-01 00:29:47,3459,E 53 St & 3 Ave,40.757632,-73.969306,530,11 Ave & W 59 St,40.771522,-73.990541,25585,Annual Membership,Subscriber,1988.0,1
38,615,2018-05-01 00:07:42,2018-05-01 00:17:58,228,E 48 St & 3 Ave,40.754601,-73.971879,3131,E 68 St & 3 Ave,40.767128,-73.962246,16038,$25 Off Annual Membership,Subscriber,1984.0,1
39,662,2018-05-01 00:08:05,2018-05-01 00:19:08,498,Broadway & W 32 St,40.748549,-73.988084,2021,W 45 St & 8 Ave,40.759291,-73.988597,31337,Annual Membership,Subscriber,1980.0,2
40,486,2018-05-01 00:08:14,2018-05-01 00:16:20,3435,Grand St & Elizabeth St,40.718822,-73.995960,347,Greenwich St & W Houston St,40.728846,-74.008591,25488,Join Citi Bike for $14.95/month,Subscriber,1968.0,1
41,2064,2018-05-01 00:08:21,2018-05-01 00:42:46,3256,Pier 40 - Hudson River Park,40.727714,-74.011296,301,E 2 St & Avenue B,40.722174,-73.983688,25047,Annual Membership,Subscriber,1980.0,2
42,472,2018-05-01 00:08:27,2018-05-01 00:16:20,3398,Smith St & 9 St,40.674696,-73.997858,310,State St & Smith St,40.689269,-73.989129,31972,Annual Membership,Subscriber,1983.0,2
43,849,2018-05-01 00:08:43,2018-05-01 00:22:53,401,Allen St & Rivington St,40.720196,-73.989978,462,W 22 St & 10 Ave,40.746920,-74.004519,29425,Annual Membership,Subscriber,1992.0,1
44,1048,2018-05-01 00:08:47,2018-05-01 00:26:15,3338,2 Ave & E 99 St,40.786259,-73.945526,3338,2 Ave & E 99 St,40.786259,-73.945526,30301,NYCHA Membership (Renewal),Subscriber,1959.0,1
45,1212,2018-05-01 00:09:09,2018-05-01 00:29:21,146,Hudson St & Reade St,40.716250,-74.009106,462,W 22 St & 10 Ave,40.746920,-74.004519,32223,3 Day,Customer,NaN,0
46,530,2018-05-01 00:09:32,2018-05-01 00:18:23,3081,Graham Ave & Grand St,40.711863,-73.944024,3108,Nassau Ave & Russell St,40.725570,-73.944340,18892,Annual Membership,Subscriber,1981.0,1
47,163,2018-05-01 00:09:48,2018-05-01 00:12:31,247,Perry St & Bleecker St,40.735354,-74.004831,3660,W 16 St & 8 Ave,40.741022,-74.001385,29800,Annual Membership,Subscriber,1975.0,1
48,1785,2018-05-01 00:09:51,2018-05-01 00:39:36,355,Bayard St & Baxter St,40.716021,-73.999744,248,Laight St & Hudson St,40.721854,-74.007718,17240,Single Ride,Customer,1983.0,1
49,1153,2018-05-01 00:09:53,2018-05-01 00:29:07,146,Hudson St & Reade St,40.716250,-74.009106,462,W 22 St & 10 Ave,40.746920,-74.004519,28185,3 Day,Customer,NaN,0

In [26]:
Data_201805.columns
#Data_201805.name_localizedValue0.unique()

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [3]:
#Pulling 201801 Data
Data_201801 = pd.read_csv('201801_citibikenyc_tripdata.csv')
Data_201801.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,name_localizedValue0,usertype,birth year,gender
0,196,2018-01-01 00:01:51,2018-01-01 00:05:07,315,South St & Gouverneur Ln,40.703554,-74.006702,259,South St & Whitehall St,40.701221,-74.012342,18534,Annual Membership,Subscriber,1997.0,1
1,207,2018-01-01 00:02:44,2018-01-01 00:06:11,3224,W 13 St & Hudson St,40.739974,-74.005139,470,W 20 St & 8 Ave,40.743453,-74.000040,19651,Annual Membership,Subscriber,1978.0,1
2,613,2018-01-01 00:03:15,2018-01-01 00:13:28,386,Centre St & Worth St,40.714948,-74.002345,2008,Little West St & 1 Pl,40.705693,-74.016777,21678,Annual Membership,Subscriber,1982.0,1
3,375,2018-01-01 00:06:44,2018-01-01 00:12:59,466,W 25 St & 6 Ave,40.743954,-73.991449,325,E 19 St & 3 Ave,40.736245,-73.984738,29822,Annual Membership,Subscriber,1982.0,1
4,402,2018-01-01 00:06:57,2018-01-01 00:13:40,438,St Marks Pl & 1 Ave,40.727791,-73.985649,380,W 4 St & 7 Ave S,40.734011,-74.002939,30722,Annual Membership,Subscriber,1989.0,1

In [27]:
Data_201801.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [4]:
#Pulling 201707 Data
Data_201707 = pd.read_csv('201707-citibike-tripdata.csv')
Data_201707.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,364,2017-07-01 00:00:00,2017-07-01 00:06:05,539,Metropolitan Ave & Bedford Ave,40.715348,-73.960241,3107,Bedford Ave & Nassau Ave,40.723117,-73.952123,14744,Subscriber,1986.0,1
1,2142,2017-07-01 00:00:03,2017-07-01 00:35:46,293,Lafayette St & E 8 St,40.730207,-73.991026,3425,2 Ave & E 104 St,40.789210,-73.943708,19587,Subscriber,1981.0,1
2,328,2017-07-01 00:00:08,2017-07-01 00:05:37,3242,Schermerhorn St & Court St,40.691029,-73.991834,3397,Court St & Nelson St,40.676395,-73.998699,27937,Subscriber,1984.0,2
3,2530,2017-07-01 00:00:11,2017-07-01 00:42:22,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,398,Atlantic Ave & Furman St,40.691652,-73.999979,26066,Subscriber,1985.0,1
4,2534,2017-07-01 00:00:15,2017-07-01 00:42:29,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,398,Atlantic Ave & Furman St,40.691652,-73.999979,29408,Subscriber,1982.0,2

In [18]:
Data_201707.columns
Data_201707.usertype.unique()

array(['Subscriber', 'Customer'], dtype=object)

In [6]:
#Pulling 201701 Data
Data_201701 = pd.read_csv('201701-citibike-tripdata.csv')
Data_201701.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,680,2017-01-01 00:00:21,2017-01-01 00:11:41,3226,W 82 St & Central Park West,40.782750,-73.971370,3165,Central Park West & W 72 St,40.775794,-73.976206,25542,Subscriber,1965.0,2
1,1282,2017-01-01 00:00:45,2017-01-01 00:22:08,3263,Cooper Square & E 7 St,40.729236,-73.990868,498,Broadway & W 32 St,40.748549,-73.988084,21136,Subscriber,1987.0,2
2,648,2017-01-01 00:00:57,2017-01-01 00:11:46,3143,5 Ave & E 78 St,40.776829,-73.963888,3152,3 Ave & E 71 St,40.768737,-73.961199,18147,Customer,NaN,0
3,631,2017-01-01 00:01:10,2017-01-01 00:11:42,3143,5 Ave & E 78 St,40.776829,-73.963888,3152,3 Ave & E 71 St,40.768737,-73.961199,21211,Customer,NaN,0
4,621,2017-01-01 00:01:25,2017-01-01 00:11:47,3143,5 Ave & E 78 St,40.776829,-73.963888,3152,3 Ave & E 71 St,40.768737,-73.961199,26819,Customer,NaN,0

In [14]:
Data_201701.columns

Index(['Trip Duration', 'Start Time', 'Stop Time', 'Start Station ID',
       'Start Station Name', 'Start Station Latitude',
       'Start Station Longitude', 'End Station ID', 'End Station Name',
       'End Station Latitude', 'End Station Longitude', 'Bike ID', 'User Type',
       'Birth Year', 'Gender'],
      dtype='object')

In [64]:
# Rename Columns
Data_201701 = Data_201701.rename(columns={'Trip Duration': 'tripduration', 'Start Time': 'starttime','Stop Time':'stoptime', 
                                          'Start Station ID' : 'start station id','Start Station Name' : 'start station name' ,
                                          'Start Station Latitude': 'start station latitude' ,'Start Station Longitude':'start station longitude',
                                          'End Station ID' : 'end station id' , 'End Station Name':'end station name',
       'End Station Latitude': 'end station latitude', 'End Station Longitude':'end station longitude', 'Bike ID':'bikeid',
                                          'User Type':'usertype' ,'Birth Year': 'birth year', 'Gender':  'gender'  })

In [65]:
#Removing Extra columns
Data_201805 = Data_201805.drop(["name_localizedValue0"],axis=1)
Data_201805.head()

ValueError: labels ['name_localizedValue0'] not contained in axis

In [23]:
Data_201801 = Data_201801.drop(["name_localizedValue0"],axis=1)
Data_201801.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,196,2018-01-01 00:01:51,2018-01-01 00:05:07,315,South St & Gouverneur Ln,40.703554,-74.006702,259,South St & Whitehall St,40.701221,-74.012342,18534,Subscriber,1997.0,1
1,207,2018-01-01 00:02:44,2018-01-01 00:06:11,3224,W 13 St & Hudson St,40.739974,-74.005139,470,W 20 St & 8 Ave,40.743453,-74.000040,19651,Subscriber,1978.0,1
2,613,2018-01-01 00:03:15,2018-01-01 00:13:28,386,Centre St & Worth St,40.714948,-74.002345,2008,Little West St & 1 Pl,40.705693,-74.016777,21678,Subscriber,1982.0,1
3,375,2018-01-01 00:06:44,2018-01-01 00:12:59,466,W 25 St & 6 Ave,40.743954,-73.991449,325,E 19 St & 3 Ave,40.736245,-73.984738,29822,Subscriber,1982.0,1
4,402,2018-01-01 00:06:57,2018-01-01 00:13:40,438,St Marks Pl & 1 Ave,40.727791,-73.985649,380,W 4 St & 7 Ave S,40.734011,-74.002939,30722,Subscriber,1989.0,1

In [63]:
Data_201801.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [68]:
#Merging files
#Stack data 
CitiBikeData = pd.concat([Data_201805,Data_201801,Data_201707,Data_201701],axis=0)
#CitiBikeData = pd.merge(Data_201805,Data_201801)

In [67]:
CitiBikeData.head(20)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,303,2018-05-01 00:00:11,2018-05-01 00:05:15,491,E 24 St & Park Ave S,40.740964,-73.986022,2003,1 Ave & E 18 St,40.733812,-73.980544,32191,Subscriber,1984.0,1
1,700,2018-05-01 00:00:36,2018-05-01 00:12:16,507,E 25 St & 2 Ave,40.739126,-73.979738,3458,W 55 St & 6 Ave,40.763094,-73.978350,29357,Subscriber,1996.0,1
2,443,2018-05-01 00:00:40,2018-05-01 00:08:04,3263,Cooper Square & Astor Pl,40.729515,-73.990753,546,E 30 St & Park Ave S,40.744449,-73.983035,27255,Subscriber,1969.0,1
3,297,2018-05-01 00:00:43,2018-05-01 00:05:41,532,S 5 Pl & S 5 St,40.710451,-73.960876,3096,Union Ave & N 12 St,40.719240,-73.952420,16980,Subscriber,1985.0,1
4,421,2018-05-01 00:01:01,2018-05-01 00:08:02,3493,E 118 St & 3 Ave,40.799139,-73.938915,3351,E 102 St & 1 Ave,40.786995,-73.941648,30645,Subscriber,1986.0,1
5,68905,2018-05-01 00:01:11,2018-05-01 19:09:36,237,E 11 St & 2 Ave,40.730473,-73.986724,504,1 Ave & E 16 St,40.732219,-73.981656,27440,Subscriber,1969.0,1
6,197,2018-05-01 00:01:17,2018-05-01 00:04:35,437,Macon St & Nostrand Ave,40.680983,-73.950048,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,31566,Subscriber,1988.0,1
7,259,2018-05-01 00:01:31,2018-05-01 00:05:50,236,St Marks Pl & 2 Ave,40.728419,-73.987140,312,Allen St & Stanton St,40.722055,-73.989111,29872,Subscriber,1996.0,2
8,359,2018-05-01 00:01:42,2018-05-01 00:07:42,3158,W 63 St & Broadway,40.771639,-73.982614,495,W 47 St & 10 Ave,40.762699,-73.993012,14824,Subscriber,1981.0,2
9,460,2018-05-01 00:02:03,2018-05-01 00:09:43,285,Broadway & E 14 St,40.734546,-73.990741,236,St Marks Pl & 2 Ave,40.728419,-73.987140,17638,Subscriber,1972.0,2
10,295,2018-05-01 00:02:04,2018-05-01 00:07:00,499,Broadway & W 60 St,40.769155,-73.981918,3175,W 70 St & Amsterdam Ave,40.777480,-73.982886,31475,Subscriber,1958.0,1
11,204,2018-05-01 00:02:17,2018-05-01 00:05:42,3146,E 81 St & 3 Ave,40.775730,-73.956753,3135,E 75 St & 3 Ave,40.771129,-73.957723,14886,Subscriber,1991.0,1
12,589,2018-05-01 00:02:22,2018-05-01 00:12:11,462,W 22 St & 10 Ave,40.746920,-74.004519,450,W 49 St & 8 Ave,40.762272,-73.987882,27251,Subscriber,1981.0,1
13,90,2018-05-01 00:02:30,2018-05-01 00:04:00,3325,E 95 St & 3 Ave,40.784903,-73.950503,3312,1 Ave & E 94 St,40.781721,-73.945940,29077,Subscriber,NaN,0
14,1596,2018-05-01 00:02:47,2018-05-01 00:29:24,439,E 4 St & 2 Ave,40.726281,-73.989780,3074,Montrose Ave & Bushwick Ave,40.707678,-73.940162,20843,Subscriber,1995.0,1
15,342,2018-05-01 00:02:52,2018-05-01 00:08:34,474,5 Ave & E 29 St,40.745168,-73.986831,293,Lafayette St & E 8 St,40.730207,-73.991026,30253,Subscriber,1991.0,1
16,905,2018-05-01 00:03:20,2018-05-01 00:18:25,3081,Graham Ave & Grand St,40.711863,-73.944024,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,30190,Subscriber,1987.0,1
17,535,2018-05-01 00:03:28,2018-05-01 00:12:23,416,Cumberland St & Lafayette Ave,40.687534,-73.972652,373,Willoughby Ave & Walworth St,40.693317,-73.953820,29359,Subscriber,1975.0,1
18,254,2018-05-01 00:03:30,2018-05-01 00:07:44,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,3087,Metropolitan Ave & Meeker Ave,40.714133,-73.952344,20523,Subscriber,1972.0,1
19,352,2018-05-01 00:03:36,2018-05-01 00:09:29,403,E 2 St & 2 Ave,40.725029,-73.990697,150,E 2 St & Avenue C,40.720874,-73.980858,25750,Subscriber,1995.0,1

In [71]:
#save to csv
CitiBikeData.to_csv('CitiBikeData.csv', index=False)

In [72]:
CitiBikeData1.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')